services:
    _defaults:
        autowire: true
        autoconfigure: true


    Becklyn\AssetsBundle\Asset\AssetsCache: ~
    Becklyn\AssetsBundle\Asset\AssetGenerator: ~
    Becklyn\AssetsBundle\Asset\AssetsRegistry: ~
    Becklyn\AssetsBundle\Processor\CssProcessor: ~
    Becklyn\AssetsBundle\Cache\CacheWarmer: ~

    Becklyn\AssetsBundle\Command\AssetsCacheCommand:
        tags:
            - { name: console.command, command: becklyn:assets:reset }

    Becklyn\AssetsBundle\Finder\AssetsFinder:
        bind:
            $projectDir: '%kernel.project_dir%'

    Becklyn\AssetsBundle\Html\AssetHtmlGenerator:
        public: true
        bind:
            $isDebug: '%kernel.debug%'

    Becklyn\AssetsBundle\Path\AssetPathHelper: ~
    Becklyn\AssetsBundle\Processor\CssProcessor: ~

    Becklyn\AssetsBundle\Processor\ProcessorRegistry:
        bind:
            $processors:
                css: '@Becklyn\AssetsBundle\Processor\CssProcessor'

    Becklyn\AssetsBundle\Twig\AssetsTwigExtension: ~

