services:
    # --------------------------------------------------------------------------------------------------------------
    # Cache
    # --------------------------------------------------------------------------------------------------------------
    becklyn.assets.cache:
        class: Becklyn\AssetsBundle\Cache\AssetCache
        arguments:
            - '%kernel.root_dir%'
            - '@becklyn.assets.cache.file'
            - '@becklyn.assets.cache.mapping'
            - '@?logger'
        public: false

    becklyn.assets.cache.file:
        class: Becklyn\AssetsBundle\Cache\FileCache
        arguments:
            - '%kernel.root_dir%'
            - '/assets/'
            - '@filesystem'
        public: false

    becklyn.assets.cache.mapping:
        class: Becklyn\AssetsBundle\Cache\MappingCache
        arguments:
            - '/assets/'
            - '@becklyn.assets.cache.mapping.io'
        public: false

    becklyn.assets.cache.mapping.io:
        class: Becklyn\AssetsBundle\Cache\MappingCache\MappingCacheIO
        arguments:
            - '%kernel.cache_dir%'
            - '@filesystem'
        public: false



    # --------------------------------------------------------------------------------------------------------------
    # File
    # --------------------------------------------------------------------------------------------------------------
    becklyn.assets.asset_file_generator:
        class: Becklyn\AssetsBundle\File\AssetFileGenerator
        arguments:
            - '%kernel.root_dir%'
        public: false



    # --------------------------------------------------------------------------------------------------------------
    # Twig Template & Asset Finder
    # --------------------------------------------------------------------------------------------------------------
    becklyn.assets.handler:
        class: Becklyn\AssetsBundle\Assets\AssetsManager
        arguments:
            - '@kernel'
            - '@becklyn.assets.cache'
            - '@becklyn.assets.template_finder'
            - '@becklyn.assets.asset_references_extractor'


    becklyn.assets.template_finder:
        class: Becklyn\AssetsBundle\Finder\TemplateFinder
        public: false

    becklyn.assets.asset_references_extractor:
        class: Becklyn\AssetsBundle\Twig\AssetReferencesExtractor
        public: false
        arguments:
            - '@twig'
            - '@?logger'

    # --------------------------------------------------------------------------------------------------------------
    # Path Generator
    # --------------------------------------------------------------------------------------------------------------
    becklyn.assets.path_generator:
        class: Becklyn\AssetsBundle\Path\PathGenerator
        arguments:
            - '@becklyn.assets.cache'
            - '%kernel.debug%'
        public: false

    # --------------------------------------------------------------------------------------------------------------
    # Bundle Internal Twig Extensions
    # --------------------------------------------------------------------------------------------------------------
    becklyn.assets.twig_extension:
        class: Becklyn\AssetsBundle\Twig\Extension\AssetsTwigExtension
        arguments:
            - '@becklyn.assets.path_generator'
        public: false
        tags:
            - { name: twig.extension }
