services:
    # --------------------------------------------------------------------------------------------------------------
    # Cache
    # --------------------------------------------------------------------------------------------------------------
    becklyn.assets.cache:
        class: Becklyn\AssetsBundle\Cache\AssetCache
        arguments:
            - '%kernel.cache_dir%'

    # --------------------------------------------------------------------------------------------------------------
    # Twig Template & Asset Finder
    # --------------------------------------------------------------------------------------------------------------
    becklyn.assets.twig_template_finder:
        class: Becklyn\AssetsBundle\Finder\TwigTemplateFinder
        arguments:
            - '@kernel'
            - '@becklyn.assets.twig_assets_finder'

    becklyn.assets.twig_assets_finder:
        class: Becklyn\AssetsBundle\Finder\TwigAssetsFinder
        arguments:
            - '@twig'
            - '@templating.name_parser'
            - '@templating.locator'
            - '@filesystem'

    # --------------------------------------------------------------------------------------------------------------
    # Path Generator
    # --------------------------------------------------------------------------------------------------------------
    becklyn.assets.path_generator:
        class: Becklyn\AssetsBundle\Path\PathGenerator
        arguments:
            - '@becklyn.assets.cache'
            - '@assets.packages'
            - '%kernel.debug%'
        public: false

    # --------------------------------------------------------------------------------------------------------------
    # Bundle Internal Twig Extensions
    # --------------------------------------------------------------------------------------------------------------
    becklyn.assets.twig_extension:
        class: Becklyn\AssetsBundle\Twig\Extension\AssetsTwigExtension
        arguments:
            - '@becklyn.assets.path_generator'
        public: false
        tags:
            - { name: twig.extension }
