services:
    # --------------------------------------------------------------------------------------------------------------
    # Cache
    # --------------------------------------------------------------------------------------------------------------
    becklyn.assets.cache:
        class: Becklyn\AssetsBundle\Cache\AssetCache
        arguments:
            - '%kernel.root_dir%'
            - '%kernel.cache_dir%'
            - '/assets/'
            - '@?logger'
        public: false

    # --------------------------------------------------------------------------------------------------------------
    # Twig Template & Asset Finder
    # --------------------------------------------------------------------------------------------------------------
    becklyn.assets.handler:
        class: Becklyn\AssetsBundle\Handler\AssetHandler
        arguments:
            - '@kernel'
            - '@becklyn.assets.cache'
            - '@becklyn.assets.template_finder'
            - '@becklyn.assets.asset_references_extractor'


    becklyn.assets.template_finder:
        class: Becklyn\AssetsBundle\Finder\TemplateFinder
        public: false

    becklyn.assets.asset_references_extractor:
        class: Becklyn\AssetsBundle\Twig\AssetReferencesExtractor
        public: false
        arguments:
            - '@twig'
            - '@?logger'

    # --------------------------------------------------------------------------------------------------------------
    # Path Generator
    # --------------------------------------------------------------------------------------------------------------
    becklyn.assets.path_generator:
        class: Becklyn\AssetsBundle\Path\PathGenerator
        arguments:
            - '@becklyn.assets.cache'
            - '%kernel.debug%'
        public: false

    # --------------------------------------------------------------------------------------------------------------
    # Bundle Internal Twig Extensions
    # --------------------------------------------------------------------------------------------------------------
    becklyn.assets.twig_extension:
        class: Becklyn\AssetsBundle\Twig\Extension\AssetsTwigExtension
        arguments:
            - '@becklyn.assets.path_generator'
        public: false
        tags:
            - { name: twig.extension }
