services:
    _defaults:
        autowire: true
        autoconfigure: true


    Becklyn\AssetsBundle\Asset\AssetsCache: ~

    Becklyn\AssetsBundle\Asset\AssetGenerator:
        $publicPath: "%kernel.project_dir%/public"
        $outputDir: "assets"

    Becklyn\AssetsBundle\Asset\AssetsRegistry: ~
    Becklyn\AssetsBundle\Cache\CacheWarmer: ~

    Becklyn\AssetsBundle\Command\AssetsCacheCommand:
        tags:
            - { name: console.command, command: becklyn:assets:reset }

    Becklyn\AssetsBundle\Controller\EmbedController:
        arguments:
            $isDebug: '%kernel.debug%'
        public: true

    Becklyn\AssetsBundle\Entry\EntryNamespaces:
        $projectDir: '%kernel.project_dir%'

    Becklyn\AssetsBundle\File\ExtensionMimeTypeGuesser: ~
    Becklyn\AssetsBundle\Finder\AssetsFinder: ~

    Becklyn\AssetsBundle\Html\AssetHtmlGenerator:
        public: true
        arguments:
            $isDebug: '%kernel.debug%'

    Becklyn\AssetsBundle\Path\AssetPathHelper: ~
    Becklyn\AssetsBundle\Processor\CssProcessor: ~

    Becklyn\AssetsBundle\Processor\ProcessorRegistry:
        arguments:
            $processors:
                css: '@Becklyn\AssetsBundle\Processor\CssProcessor'

    Becklyn\AssetsBundle\Twig\AssetsTwigExtension: ~

