services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $isDebug: '%kernel.debug%'
            $projectDir: '%kernel.project_dir%'

    Becklyn\AssetsBundle\:
        resource: '../../*'
        exclude: '../../{Asset/Asset.php,Data,DependencyInjection,Exception,Resources,BecklynAssetsBundle.php}'

    Becklyn\AssetsBundle\Controller\EmbedController:
        public: true

    Becklyn\AssetsBundle\File\FileTypeRegistry:
        $specializedFileTypes:
            css: '@Becklyn\AssetsBundle\File\Type\CssFile'
            js: '@Becklyn\AssetsBundle\File\Type\JavaScriptFile'
            svg: '@Becklyn\AssetsBundle\File\Type\SvgFile'

    Becklyn\AssetsBundle\Html\AssetHtmlGenerator:
        public: true

    # Register route loader
    Becklyn\AssetsBundle\RouteLoader\AssetsRouteLoader:
        public: true
        tags: [routing.loader]
