services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $isDebug: '%kernel.debug%'
            $projectDir: '%kernel.project_dir%'

    Becklyn\AssetsBundle\:
        resource: '../../*'
        exclude: '../../{Asset/Asset.php,Data,DependencyInjection,Exception,Resources,BecklynAssetsBundle.php}'

    Becklyn\AssetsBundle\Controller\EmbedController:
        public: true

    Becklyn\AssetsBundle\File\FileTypeRegistry:
        $specializedFileTypes: !tagged_locator { tag: becklyn_assets.file_type, default_index_method: supportsExtension }

    Becklyn\AssetsBundle\Html\AssetHtmlGenerator:
        public: true

    # Register route loader
    Becklyn\AssetsBundle\RouteLoader\AssetsRouteLoader:
        public: true
        tags: [routing.loader]
